-- P1-03 (FR-16, BR-34): sensitive actions, appended and never changed. Values are kept raw, an item status code or a
-- price in VND, so screens and reports turn them into words and money themselves.
CREATE TABLE audit_entry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(30)  NOT NULL CONSTRAINT ck_audit_entry_action CHECK (action IN ('ITEM_CANCELLED', 'MANUAL_CONFIRMATION', 'PRICE_CHANGED')),
    employee_id  BIGINT       NOT NULL REFERENCES employee (id),
    order_id     BIGINT       REFERENCES orders (id),
    subject      VARCHAR(200) NOT NULL,
    before_value VARCHAR(100),
    after_value  VARCHAR(100),
    amount       BIGINT,
    reason       VARCHAR(300),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_entry_created ON audit_entry (created_at DESC);

-- BR-34: no edit and no delete, not even in SQL. Only the owner of the table, by dropping the triggers, could.
CREATE FUNCTION audit_entry_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_entry is append-only';
END;
$$;
CREATE TRIGGER tr_audit_entry_append_only BEFORE UPDATE OR DELETE ON audit_entry
    FOR EACH ROW EXECUTE FUNCTION audit_entry_append_only();
CREATE TRIGGER tr_audit_entry_no_truncate BEFORE TRUNCATE ON audit_entry
    FOR EACH STATEMENT EXECUTE FUNCTION audit_entry_append_only();
