-- P1-04 (FR-08.10, FR-08.11, BR-35): a discount on a whole bill or a dish given free, with a reason, waiting for a
-- manager when past the limit. The total of an order now subtracts the adjustments in effect (BR-12).
CREATE TABLE adjustment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT       NOT NULL REFERENCES orders (id),
    order_item_id BIGINT       REFERENCES order_item (id),
    type          VARCHAR(20)  NOT NULL CHECK (type IN ('DISCOUNT', 'COMP')),
    amount        BIGINT       NOT NULL CHECK (amount > 0),
    reason        VARCHAR(20)  NOT NULL CHECK (reason IN ('WAIT', 'FOOD_QUALITY', 'STAFF_ERROR', 'PROMOTION', 'OTHER')),
    note          VARCHAR(300),
    status        VARCHAR(20)  NOT NULL CHECK (status IN ('PENDING', 'APPLIED', 'REJECTED', 'CANCELLED')),
    created_by    BIGINT       NOT NULL REFERENCES employee (id),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    decided_by    BIGINT       REFERENCES employee (id),
    decided_at    TIMESTAMPTZ,
    CONSTRAINT ck_adjustment_comp_item CHECK ((type = 'COMP') = (order_item_id IS NOT NULL)),
    CONSTRAINT ck_adjustment_other_note CHECK (reason <> 'OTHER' OR note IS NOT NULL)
);
-- BR-35: a dish is given free once at a time.
CREATE UNIQUE INDEX ux_adjustment_comp_item ON adjustment (order_item_id) WHERE status IN ('PENDING', 'APPLIED');
CREATE INDEX ix_adjustment_order ON adjustment (order_id);
CREATE INDEX ix_adjustment_pending ON adjustment (created_at) WHERE status = 'PENDING';

-- BR-34: a discount that takes effect is written to the audit log too.
ALTER TABLE audit_entry DROP CONSTRAINT ck_audit_entry_action;
ALTER TABLE audit_entry ADD CONSTRAINT ck_audit_entry_action
    CHECK (action IN ('ITEM_CANCELLED', 'MANUAL_CONFIRMATION', 'PRICE_CHANGED', 'DISCOUNT_GIVEN'));
