-- P1-01 (FR-04.5, FR-04.6, BR-04, BR-36): an order may hold several tables, and moving between tables keeps the
-- bill. One row per table an order holds or held: released_at stays null while it holds it, so the rows are also
-- the history of moves. orders.table_id stays as the main table, and ux_orders_open_table keeps two phones opening
-- the same table from creating two orders.
CREATE TABLE order_table (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL REFERENCES orders (id),
    table_id    BIGINT      NOT NULL REFERENCES dining_table (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    released_at TIMESTAMPTZ
);
-- BR-04: a table belongs to at most one open order.
CREATE UNIQUE INDEX ux_order_table_active ON order_table (table_id) WHERE released_at IS NULL;
CREATE INDEX ix_order_table_order ON order_table (order_id);

-- Every order so far held its one table from opening to closing.
INSERT INTO order_table (order_id, table_id, created_at, released_at)
SELECT id, table_id, opened_at, closed_at FROM orders WHERE table_id IS NOT NULL;
