-- P2-03 (FR-09.5 → FR-09.7, BR-37): suppliers, goods receipts with prices, and the cost of each ingredient.
CREATE TABLE supplier (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(150) NOT NULL UNIQUE,
    phone    VARCHAR(20),
    address  VARCHAR(300),
    tax_code VARCHAR(20),
    note     VARCHAR(300),
    active   BOOLEAN      NOT NULL DEFAULT TRUE
);

-- BR-37: a receipt is never edited or deleted once saved.
CREATE TABLE goods_receipt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT      NOT NULL REFERENCES supplier (id),
    note        VARCHAR(300),
    created_by  BIGINT      NOT NULL REFERENCES employee (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_goods_receipt_created ON goods_receipt (created_at DESC);

CREATE TABLE receipt_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id        BIGINT         NOT NULL REFERENCES goods_receipt (id),
    inventory_item_id BIGINT         NOT NULL REFERENCES inventory_item (id),
    quantity          NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
    unit_price        BIGINT         NOT NULL CHECK (unit_price >= 0)
);
CREATE INDEX ix_receipt_line_receipt ON receipt_line (receipt_id);

-- BR-37: the cost of one unit, the weighted average of what was paid for it; null until the first receipt.
ALTER TABLE inventory_item ADD COLUMN unit_cost BIGINT CHECK (unit_cost >= 0);

-- The receipt a movement came from; null for movements entered by hand.
ALTER TABLE stock_movement ADD COLUMN goods_receipt_id BIGINT REFERENCES goods_receipt (id);
