-- P2-02: dish recipes, and stock used up automatically when a dish goes to the kitchen (FR-09.8 → FR-09.10, BR-38).

-- How much of each ingredient one portion of a dish takes, in the ingredient's own unit.
-- A dish can only be deleted while it has never been ordered (BR-18), and its recipe goes with it.
CREATE TABLE recipe_line (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id      BIGINT         NOT NULL REFERENCES menu_item (id) ON DELETE CASCADE,
    inventory_item_id BIGINT         NOT NULL REFERENCES inventory_item (id),
    quantity          NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
    CONSTRAINT ux_recipe_line_item UNIQUE (menu_item_id, inventory_item_id)
);

-- SALE: stock used by a dish sent to the kitchen, or given back when it is cancelled before cooking.
ALTER TABLE stock_movement DROP CONSTRAINT stock_movement_type_check;
ALTER TABLE stock_movement ADD CONSTRAINT ck_stock_movement_type CHECK (type IN ('IN', 'OUT', 'ADJUST', 'SALE'));
ALTER TABLE stock_movement ADD COLUMN order_item_id BIGINT REFERENCES order_item (id);
CREATE INDEX ix_stock_movement_order_item ON stock_movement (order_item_id) WHERE order_item_id IS NOT NULL;
CREATE INDEX ix_stock_movement_created ON stock_movement (created_at);

-- A dish going to the kitchen is never held back by a stock count that is off, so stock may now go below zero.
-- Moving stock out by hand and counting it still cannot (InventoryService).
ALTER TABLE inventory_item DROP CONSTRAINT inventory_item_quantity_check;
