-- P2-01: shifts of the one cash drawer, cash paid out of it, and the cash taken in each shift (FR-17, BR-39).

-- A shift is open while closed_at is empty; closing records the expected cash next to the count, and a reason when
-- they differ. Nothing is changed afterwards.
CREATE TABLE cash_shift (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opened_by     BIGINT       NOT NULL REFERENCES employee (id),
    opened_at     TIMESTAMPTZ  NOT NULL,
    opening_float BIGINT       NOT NULL CHECK (opening_float >= 0),
    closed_by     BIGINT       REFERENCES employee (id),
    closed_at     TIMESTAMPTZ,
    expected_cash BIGINT,
    counted_cash  BIGINT       CHECK (counted_cash >= 0),
    close_note    VARCHAR(300),
    CONSTRAINT ck_cash_shift_closed CHECK ((closed_at IS NULL) = (closed_by IS NULL) AND (closed_at IS NULL) = (expected_cash IS NULL) AND (closed_at IS NULL) = (counted_cash IS NULL)),
    CONSTRAINT ck_cash_shift_reason CHECK (counted_cash = expected_cash OR close_note IS NOT NULL)
);
-- One drawer, so at most one open shift.
CREATE UNIQUE INDEX ux_cash_shift_open ON cash_shift ((closed_at IS NULL)) WHERE closed_at IS NULL;
CREATE INDEX ix_cash_shift_opened ON cash_shift (opened_at DESC);

CREATE TABLE cash_expense (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_shift_id BIGINT       NOT NULL REFERENCES cash_shift (id),
    amount        BIGINT       NOT NULL CHECK (amount > 0),
    reason        VARCHAR(300) NOT NULL,
    created_by    BIGINT       NOT NULL REFERENCES employee (id),
    created_at    TIMESTAMPTZ  NOT NULL
);
CREATE INDEX ix_cash_expense_shift ON cash_expense (cash_shift_id);

-- Cash taken from now on belongs to the shift that was open; transfers never do. Older cash has no shift.
ALTER TABLE payment ADD COLUMN cash_shift_id BIGINT REFERENCES cash_shift (id);
ALTER TABLE payment ADD CONSTRAINT ck_payment_cash_shift CHECK (cash_shift_id IS NULL OR method = 'CASH');
CREATE INDEX ix_payment_cash_shift ON payment (cash_shift_id) WHERE cash_shift_id IS NOT NULL;
