-- P4-01: bookings, their deposits by bank transfer, and the order a booking opens when the guests arrive (FR-18, BR-42).

-- The code is also the transfer content of the deposit, so the SePay webhook finds the booking as it finds a bill.
-- A deposit is held money, not revenue: deposit_applied records what came off the bill when the order was paid.
CREATE TABLE reservation (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(20)   NOT NULL UNIQUE,
    guest_name           VARCHAR(100)  NOT NULL,
    phone                VARCHAR(20)   NOT NULL,
    reserved_at          TIMESTAMPTZ   NOT NULL,
    guest_count          INTEGER       NOT NULL CHECK (guest_count BETWEEN 1 AND 200),
    table_id             BIGINT        REFERENCES dining_table (id),
    note                 VARCHAR(300),
    status               VARCHAR(20)   NOT NULL CHECK (status IN ('BOOKED', 'SEATED', 'CANCELLED', 'NO_SHOW')),
    deposit_amount       BIGINT        NOT NULL DEFAULT 0 CHECK (deposit_amount >= 0),
    deposit_paid_at      TIMESTAMPTZ,
    deposit_confirmation VARCHAR(10)   CHECK (deposit_confirmation IN ('AUTO', 'MANUAL')),
    deposit_confirmed_by BIGINT        REFERENCES employee (id),
    deposit_applied      BIGINT        CHECK (deposit_applied >= 0),
    confirmation_text    VARCHAR(1000),
    confirmation_sent_at TIMESTAMPTZ,
    created_by           BIGINT        NOT NULL REFERENCES employee (id),
    created_at           TIMESTAMPTZ   NOT NULL,
    CONSTRAINT ck_reservation_deposit_paid CHECK ((deposit_paid_at IS NULL) = (deposit_confirmation IS NULL)),
    CONSTRAINT ck_reservation_deposit_due CHECK (deposit_paid_at IS NULL OR deposit_amount > 0)
);
CREATE INDEX ix_reservation_reserved ON reservation (reserved_at);

-- One order per booking at most.
ALTER TABLE orders ADD COLUMN reservation_id BIGINT UNIQUE REFERENCES reservation (id);

-- The bank transfer that brought a deposit in, beside the one that paid a bill.
ALTER TABLE bank_transaction ADD COLUMN reservation_id BIGINT REFERENCES reservation (id);
