-- BNN-RMS core schema. Money is VND in BIGINT; time is TIMESTAMPTZ.

CREATE TABLE employee (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'WAITER', 'CHEF', 'CASHIER')),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    sort_order INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE menu_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL REFERENCES category (id),
    name        VARCHAR(150) NOT NULL,
    price       BIGINT       NOT NULL CHECK (price >= 0),
    description VARCHAR(500),
    available   BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_menu_item_category ON menu_item (category_id);

CREATE TABLE dining_table (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE,
    area     VARCHAR(50),
    seats    INTEGER     NOT NULL CHECK (seats > 0),
    qr_token VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(20) NOT NULL CHECK (type IN ('DINE_IN', 'TAKEAWAY')),
    status      VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'PAID', 'CANCELLED')),
    table_id    BIGINT REFERENCES dining_table (id),
    guest_count INTEGER CHECK (guest_count > 0),
    note        VARCHAR(500),
    created_by  BIGINT REFERENCES employee (id),
    opened_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at   TIMESTAMPTZ,
    CONSTRAINT ck_orders_table CHECK (type = 'TAKEAWAY' OR table_id IS NOT NULL)
);
-- BR-04: at most one open order per table.
CREATE UNIQUE INDEX ux_orders_open_table ON orders (table_id) WHERE status = 'OPEN';
CREATE INDEX ix_orders_status ON orders (status);

CREATE TABLE order_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT       NOT NULL REFERENCES orders (id),
    menu_item_id  BIGINT       NOT NULL REFERENCES menu_item (id),
    item_name     VARCHAR(150) NOT NULL,
    unit_price    BIGINT       NOT NULL CHECK (unit_price >= 0),
    quantity      INTEGER      NOT NULL CHECK (quantity BETWEEN 1 AND 50),
    note          VARCHAR(300),
    status        VARCHAR(20)  NOT NULL CHECK (status IN ('PENDING', 'WAITING', 'COOKING', 'READY', 'SERVED', 'CANCELLED')),
    source        VARCHAR(10)  NOT NULL CHECK (source IN ('STAFF', 'GUEST')),
    cancel_reason VARCHAR(300),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    sent_at       TIMESTAMPTZ,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_order_item_order ON order_item (order_id);
CREATE INDEX ix_order_item_active ON order_item (status) WHERE status IN ('PENDING', 'WAITING', 'COOKING', 'READY');

CREATE TABLE payment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT      NOT NULL REFERENCES orders (id),
    method          VARCHAR(20) NOT NULL CHECK (method IN ('CASH', 'BANK_TRANSFER')),
    status          VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
    amount          BIGINT      NOT NULL CHECK (amount >= 0),
    reference       VARCHAR(20) UNIQUE,
    received_amount BIGINT,
    confirmation    VARCHAR(10) CHECK (confirmation IN ('AUTO', 'MANUAL')),
    confirmed_by    BIGINT REFERENCES employee (id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    paid_at         TIMESTAMPTZ
);
-- BR-14: one pending transfer per order. BR-13: never paid twice.
CREATE UNIQUE INDEX ux_payment_pending_order ON payment (order_id) WHERE status = 'PENDING';
CREATE UNIQUE INDEX ux_payment_paid_order ON payment (order_id) WHERE status = 'PAID';
CREATE INDEX ix_payment_paid_at ON payment (paid_at) WHERE status = 'PAID';

CREATE TABLE bank_transaction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_txn_id VARCHAR(50) NOT NULL UNIQUE, -- BR-16: SePay "id", processed once
    gateway         VARCHAR(50),
    account_number  VARCHAR(30),
    amount          BIGINT      NOT NULL,
    content         VARCHAR(500),
    code            VARCHAR(50),
    transfer_type   VARCHAR(10) NOT NULL,
    match_status    VARCHAR(20) NOT NULL CHECK (match_status IN ('MATCHED', 'UNMATCHED', 'IGNORED')),
    note            VARCHAR(200),
    payment_id      BIGINT REFERENCES payment (id),
    received_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_bank_transaction_status ON bank_transaction (match_status);

CREATE TABLE inventory_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)   NOT NULL UNIQUE,
    unit         VARCHAR(20)    NOT NULL,
    quantity     NUMERIC(12, 3) NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    min_quantity NUMERIC(12, 3) NOT NULL DEFAULT 0 CHECK (min_quantity >= 0)
);

CREATE TABLE stock_movement (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT         NOT NULL REFERENCES inventory_item (id),
    type              VARCHAR(10)    NOT NULL CHECK (type IN ('IN', 'OUT', 'ADJUST')),
    quantity_change   NUMERIC(12, 3) NOT NULL,
    quantity_after    NUMERIC(12, 3) NOT NULL,
    note              VARCHAR(300),
    created_by        BIGINT REFERENCES employee (id), -- null only for the opening balance in V2
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now()
);
CREATE INDEX ix_stock_movement_item ON stock_movement (inventory_item_id, created_at DESC);

CREATE TABLE restaurant_settings (
    id                INTEGER PRIMARY KEY CHECK (id = 1),
    name              VARCHAR(150) NOT NULL,
    address           VARCHAR(300),
    phone             VARCHAR(20),
    bank_code         VARCHAR(20),
    bank_account_no   VARCHAR(30),
    bank_account_name VARCHAR(100),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
