-- P4-02: guests known by their phone number, their visits, and whether they agreed to hear from us (FR-19, BR-44).

-- The number is stored normalised (10 digits from 0), so one number is one guest whatever way it was typed.
-- consent_* describe the latest agreement; opted_out_at is a refusal since then, cleared when the guest agrees again.
CREATE TABLE customer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           VARCHAR(10)  NOT NULL UNIQUE CHECK (phone ~ '^0[0-9]{9}$'),
    name            VARCHAR(100),
    note            VARCHAR(300),
    consent_channel VARCHAR(10)  CHECK (consent_channel IN ('ZALO', 'SMS')),
    consent_at      TIMESTAMPTZ,
    consent_source  VARCHAR(100),
    opted_out_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_customer_consent CHECK ((consent_at IS NULL) = (consent_channel IS NULL) AND (consent_at IS NULL) = (consent_source IS NULL))
);

ALTER TABLE orders ADD COLUMN customer_id BIGINT REFERENCES customer (id);
CREATE INDEX ix_orders_customer ON orders (customer_id) WHERE customer_id IS NOT NULL;

ALTER TABLE reservation ADD COLUMN customer_id BIGINT REFERENCES customer (id);
CREATE INDEX ix_reservation_customer ON reservation (customer_id) WHERE customer_id IS NOT NULL;
