-- P4-03: e-invoice data for every bill paid in full, exported for MISA meInvoice, and the symbol and number each was
-- issued under (FR-20, BR-45, BR-46).

-- Menu prices include VAT. The tax in a price depends on the dish's tax category and on the rate in force the day the
-- bill is paid, so a new rate is a new row from its first day, not a change of code.
CREATE TABLE tax_category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE tax_rate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_category_id BIGINT NOT NULL REFERENCES tax_category (id),
    rate            INT    NOT NULL CHECK (rate IN (0, 5, 8, 10)),
    effective_from  DATE   NOT NULL,
    UNIQUE (tax_category_id, effective_from)
);

-- The rates in force when this was written: 8% for food and drink, cut from 10% until the end of 2026, and 10% for beer
-- and spirits, which the cut leaves out. The accountant confirms them and sets the rate from 2027 once it is known.
INSERT INTO tax_category (name) VALUES ('Ăn uống'), ('Rượu, bia');
INSERT INTO tax_rate (tax_category_id, rate, effective_from)
SELECT id, CASE WHEN name = 'Ăn uống' THEN 8 ELSE 10 END, DATE '2025-07-01' FROM tax_category;

-- Every dish is food and drink, except those named as beer or spirits; the manager corrects the rest on the menu page.
ALTER TABLE menu_item ADD COLUMN tax_category_id BIGINT REFERENCES tax_category (id);
UPDATE menu_item SET tax_category_id = (SELECT id FROM tax_category WHERE name = 'Ăn uống');
UPDATE menu_item SET tax_category_id = (SELECT id FROM tax_category WHERE name = 'Rượu, bia')
WHERE name ILIKE 'bia %' OR name ILIKE 'rượu %';
ALTER TABLE menu_item ALTER COLUMN tax_category_id SET NOT NULL;

-- One per order paid in full, with the data as it stood then (BR-46). The e-invoice is not the bill: it waits to be
-- exported, then is issued on MISA under a symbol and number. Amounts in VND, VAT included in total; the deposit taken
-- off the bill counts as paid. No buyer name: a walk-in guest.
CREATE TABLE einvoice (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT       NOT NULL UNIQUE REFERENCES orders (id),
    invoice_date   TIMESTAMPTZ  NOT NULL,
    payment_method VARCHAR(5)   NOT NULL CHECK (payment_method IN ('TM', 'CK', 'TM/CK')),
    buyer_name     VARCHAR(200),
    buyer_tax_code VARCHAR(14)  CHECK (buyer_tax_code ~ '^([0-9]{10}(-[0-9]{3})?|[0-9]{12})$'),
    buyer_address  VARCHAR(300),
    buyer_email    VARCHAR(100),
    before_tax     BIGINT       NOT NULL,
    tax_amount     BIGINT       NOT NULL,
    total          BIGINT       NOT NULL CHECK (total >= 0),
    exported_at    TIMESTAMPTZ,
    invoice_symbol VARCHAR(7)   CHECK (invoice_symbol ~ '^[1-9][CK][0-9]{2}[A-Z][A-Z0-9]{2}$'),
    invoice_no     VARCHAR(8)   CHECK (invoice_no ~ '^[1-9][0-9]{0,7}$'),
    issued_by      BIGINT       REFERENCES employee (id),
    issued_at      TIMESTAMPTZ,
    CONSTRAINT ck_einvoice_total CHECK (before_tax + tax_amount = total),
    CONSTRAINT ck_einvoice_buyer CHECK (buyer_name IS NOT NULL OR (buyer_tax_code IS NULL AND buyer_address IS NULL AND buyer_email IS NULL)),
    CONSTRAINT ck_einvoice_issued CHECK ((invoice_no IS NULL) = (invoice_symbol IS NULL) AND (invoice_no IS NULL) = (issued_by IS NULL) AND (invoice_no IS NULL) = (issued_at IS NULL)),
    CONSTRAINT ux_einvoice_number UNIQUE (invoice_symbol, invoice_no)
);
CREATE INDEX ix_einvoice_date ON einvoice (invoice_date);

-- The lines as they stood when the bill was paid: a dish (GOODS), or a dish given free or a discount (DISCOUNT), which
-- comes off the total. amount = before_tax + tax_amount, VAT included like the menu prices.
CREATE TABLE einvoice_line (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    einvoice_id BIGINT       NOT NULL REFERENCES einvoice (id),
    line_no     INT          NOT NULL,
    kind        VARCHAR(10)  NOT NULL CHECK (kind IN ('GOODS', 'DISCOUNT')),
    item_name   VARCHAR(200) NOT NULL,
    unit        VARCHAR(20),
    quantity    INT          CHECK (quantity > 0),
    unit_price  BIGINT       CHECK (unit_price >= 0),
    tax_rate    INT          NOT NULL CHECK (tax_rate IN (0, 5, 8, 10)),
    amount      BIGINT       NOT NULL CHECK (amount >= 0),
    before_tax  BIGINT       NOT NULL,
    tax_amount  BIGINT       NOT NULL,
    CONSTRAINT ck_einvoice_line_amount CHECK (before_tax + tax_amount = amount),
    CONSTRAINT ck_einvoice_line_goods CHECK ((kind = 'GOODS') = (quantity IS NOT NULL) AND (quantity IS NULL) = (unit_price IS NULL) AND (quantity IS NULL) = (unit IS NULL)),
    UNIQUE (einvoice_id, line_no)
);
