-- P2-06 (FR-13.1 → 13.4, BR-23): shift templates and the weekly schedule.

CREATE TABLE work_shift (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL UNIQUE,
    start_time TIME        NOT NULL,
    end_time   TIME        NOT NULL,
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    -- BR-23: a shift never crosses midnight.
    CONSTRAINT ck_work_shift_time CHECK (end_time > start_time)
);

CREATE TABLE shift_assignment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT      NOT NULL REFERENCES employee (id),
    work_shift_id BIGINT      NOT NULL REFERENCES work_shift (id),
    work_date     DATE        NOT NULL,
    created_by    BIGINT      NOT NULL REFERENCES employee (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ux_shift_assignment UNIQUE (employee_id, work_date, work_shift_id)
);
CREATE INDEX ix_shift_assignment_date ON shift_assignment (work_date);

-- Common shifts to start with; managers can rename them or add more.
INSERT INTO work_shift (name, start_time, end_time) VALUES
    ('Sáng', '07:00', '14:00'),
    ('Chiều', '14:00', '22:00'),
    ('Hành chính', '08:00', '17:00');
