-- P2-07 (FR-14, BR-25): clocking in and out.

CREATE TABLE attendance (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         BIGINT      NOT NULL REFERENCES employee (id),
    shift_assignment_id BIGINT      REFERENCES shift_assignment (id), -- null for work a manager adds outside the schedule
    check_in_at         TIMESTAMPTZ NOT NULL,
    check_out_at        TIMESTAMPTZ,
    late_minutes        INTEGER     NOT NULL DEFAULT 0 CHECK (late_minutes >= 0),
    early_minutes       INTEGER     NOT NULL DEFAULT 0 CHECK (early_minutes >= 0),
    worked_minutes      INTEGER     CHECK (worked_minutes >= 0),
    edit_reason         VARCHAR(300),
    edited_by           BIGINT      REFERENCES employee (id),
    edited_at           TIMESTAMPTZ,
    CONSTRAINT ck_attendance_times CHECK (check_out_at IS NULL OR check_out_at > check_in_at)
);
-- BR-25: at most one open clock-in per person, and one clock-in per scheduled shift.
CREATE UNIQUE INDEX ux_attendance_open ON attendance (employee_id) WHERE check_out_at IS NULL;
CREATE UNIQUE INDEX ux_attendance_assignment ON attendance (shift_assignment_id) WHERE shift_assignment_id IS NOT NULL;
CREATE INDEX ix_attendance_employee ON attendance (employee_id, check_in_at);
