-- P2-08 (FR-13.5, 13.6, BR-24): leave requests.

CREATE TABLE leave_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL REFERENCES employee (id),
    from_date     DATE         NOT NULL,
    to_date       DATE         NOT NULL,
    type          VARCHAR(10)  NOT NULL CHECK (type IN ('PAID', 'UNPAID')),
    reason        VARCHAR(300) NOT NULL,
    status        VARCHAR(20)  NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    decided_by    BIGINT       REFERENCES employee (id),
    decision_note VARCHAR(300),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    decided_at    TIMESTAMPTZ,
    CONSTRAINT ck_leave_dates CHECK (to_date >= from_date)
);
CREATE INDEX ix_leave_request_pending ON leave_request (status) WHERE status = 'PENDING';
CREATE INDEX ix_leave_request_employee ON leave_request (employee_id, from_date);
