-- P2-09 (FR-15, BR-26, BR-27): monthly payroll.

CREATE TABLE payroll (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period        VARCHAR(7)  NOT NULL UNIQUE, -- YYYY-MM
    standard_days INTEGER     NOT NULL DEFAULT 26 CHECK (standard_days BETWEEN 1 AND 31),
    status        VARCHAR(10) NOT NULL CHECK (status IN ('DRAFT', 'FINALIZED')),
    created_by    BIGINT      NOT NULL REFERENCES employee (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    finalized_by  BIGINT      REFERENCES employee (id),
    finalized_at  TIMESTAMPTZ,
    CONSTRAINT ck_payroll_period CHECK (period ~ '^[0-9]{4}-(0[1-9]|1[0-2])$')
);

CREATE TABLE payslip (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id        BIGINT      NOT NULL REFERENCES payroll (id),
    employee_id       BIGINT      NOT NULL REFERENCES employee (id),
    pay_type          VARCHAR(10) NOT NULL CHECK (pay_type IN ('HOURLY', 'MONTHLY')),
    pay_rate          BIGINT      NOT NULL CHECK (pay_rate >= 0),
    worked_minutes    INTEGER     NOT NULL CHECK (worked_minutes >= 0),
    work_days         INTEGER     NOT NULL CHECK (work_days >= 0),
    paid_leave_days   INTEGER     NOT NULL CHECK (paid_leave_days >= 0),
    base_amount       BIGINT      NOT NULL CHECK (base_amount >= 0),
    adjustment_amount BIGINT      NOT NULL DEFAULT 0,
    net_amount        BIGINT      NOT NULL,
    CONSTRAINT ux_payslip_employee UNIQUE (payroll_id, employee_id),
    -- BR-26: net pay adds up and is never negative.
    CONSTRAINT ck_payslip_net CHECK (net_amount = base_amount + adjustment_amount AND net_amount >= 0)
);

CREATE TABLE pay_adjustment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id BIGINT       NOT NULL REFERENCES payslip (id),
    amount     BIGINT       NOT NULL CHECK (amount <> 0), -- bonus if positive, deduction if negative
    reason     VARCHAR(300) NOT NULL,
    created_by BIGINT       NOT NULL REFERENCES employee (id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_pay_adjustment_payslip ON pay_adjustment (payslip_id);
