-- P1-05 (FR-06.6, FR-06.7, BR-29): a guest calls a waiter or asks for the bill from the table QR page.
-- A request waits until a waiter takes it; handled_at - created_at is how long the guest waited.

CREATE TABLE service_request (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id   BIGINT      NOT NULL REFERENCES dining_table (id) ON DELETE CASCADE,
    type       VARCHAR(20) NOT NULL CHECK (type IN ('CALL_STAFF', 'BILL')),
    created_at TIMESTAMPTZ NOT NULL,
    handled_by BIGINT      REFERENCES employee (id),
    handled_at TIMESTAMPTZ,
    CONSTRAINT ck_service_request_handled CHECK ((handled_by IS NULL) = (handled_at IS NULL))
);
-- BR-29: at most one waiting request of each type per table. Also serves the list of waiting requests.
CREATE UNIQUE INDEX ux_service_request_open ON service_request (table_id, type) WHERE handled_at IS NULL;
